version: '3'

services:
    mirotalkc2c:
        image: mirotalk/c2c:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mirotalkc2c
        hostname: mirotalkc2c
        volumes:
            - .env:/src/.env:ro
            # These volumes are not mandatory, uncomment if you want to use it
            # - ./frontend/:/src/frontend/:ro
            # - ./backend/:/src/backend/:ro
        restart: unless-stopped
        ports:
            - '${PORT}:${PORT}'
